version: '3'

services:

  ytdl-web-api:
    container_name: "ytdl-web-api"
    build:
      context: ./server
    ports:
      - 8000:3000
    env_file: .env
    command: npm run start
    restart: unless-stopped

  ytdl-web-web-server:
      container_name: "ytdl-web-web"
      build:
          context: ./web
      volumes:
          - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
          - 8050:80
      restart: unless-stopped
