version: '3'

services:

  ytdl-web-api:
    container_name: "ytdl-web-api"
    build:
      context: ./server
    ports:
      - 8000:3000
    volumes:
      - ./server/archive:/app/archive
    env_file: .env
    command: npm run start
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    restart: unless-stopped

  ytdl-web-web-server:
      image: nginx:1.19
      container_name: "ytdl-web-web"
      volumes:
          - ./web/public:/usr/share/nginx/html
          - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
          - 8050:80
      depends_on:
        - ytdl-web-api
      restart: unless-stopped
